version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
      docker:
        - image: cimg/node:17.2.0
      steps:
        - run:
            command: docker build -t retr-0/docker-react -f dockerfile.dev
        - run:
            command: docker run -e CI=true retr-0/docker-react npm run test