version: 2.1

<<<<<<< HEAD
run:
  - docker build -t RETR-0/docker-react -f dockerfile.dev .
run:
  - docker run -e CI=true RETR-0/docker-react npm run test
=======
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    working_directory: ~/docker-react
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - run:
            command: docker build -t retr-0/docker-react -f dockerfile.dev
      - run:
            command: docker run -e CI=true retr-0/docker-react npm run test
>>>>>>> 1ea2a02c65821f3dc3d660f34a65e3867981dde5
